/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Felipe Moura
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoTwitter = new javax.swing.JLabel();
        botaoFacebook = new javax.swing.JLabel();
        botaoInstagram = new javax.swing.JLabel();
        botaoEsqueciSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoUsuario = new javax.swing.JTextField();
        fotoTelaLogin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTwitterMouseClicked(evt);
            }
        });
        getContentPane().add(botaoTwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 210, 20));

        botaoFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFacebookMouseClicked(evt);
            }
        });
        getContentPane().add(botaoFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 50, 50));

        botaoInstagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoInstagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoInstagramMouseClicked(evt);
            }
        });
        getContentPane().add(botaoInstagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 50, 50));

        botaoEsqueciSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEsqueciSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(botaoEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 50, 50));

        campoSenha.setBackground(new java.awt.Color(183, 183, 183));
        campoSenha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoSenha.setBorder(null);
        campoSenha.setOpaque(false);
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 360, 60));

        campoUsuario.setBackground(new java.awt.Color(183, 183, 183));
        campoUsuario.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        campoUsuario.setForeground(null);
        campoUsuario.setBorder(null);
        campoUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoUsuario.setOpaque(false);
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 360, 60));

        fotoTelaLogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fotoTelaLoginn.png"))); // NOI18N
        fotoTelaLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoTelaLogin2MouseClicked(evt);
            }
        });
        getContentPane().add(fotoTelaLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void fotoTelaLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoTelaLogin2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoTelaLogin2MouseClicked

    private void botaoTwitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTwitterMouseClicked
        // TODO add your handling code here:
         // Faz o evento de clicar no link
        try {
        Desktop.getDesktop().browse(new URI("https://twitter.com"));
    } catch (IOException | URISyntaxException ex) {
    }       
        
        
    }//GEN-LAST:event_botaoTwitterMouseClicked

    private void botaoInstagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoInstagramMouseClicked
  // Faz o evento de clicar no link
        try {
        Desktop.getDesktop().browse(new URI("https://instagram.com"));
    } catch (IOException | URISyntaxException ex) {
    }           // TODO add your handling code here:
    }//GEN-LAST:event_botaoInstagramMouseClicked

    private void botaoFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFacebookMouseClicked
  // Faz o evento de clicar no link
        try {
        Desktop.getDesktop().browse(new URI("https://facebook.com"));
    } catch (IOException | URISyntaxException ex) {
    }           // TODO add your handling code here:
    }//GEN-LAST:event_botaoFacebookMouseClicked

    private void botaoEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEsqueciSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEsqueciSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoEsqueciSenha;
    private javax.swing.JLabel botaoFacebook;
    private javax.swing.JLabel botaoInstagram;
    private javax.swing.JLabel botaoTwitter;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel fotoTelaLogin2;
    // End of variables declaration//GEN-END:variables
}
